---


exp:  resnet_ada_exp21
seed: 42

loader:
  norm_method: global_minmax
  train_batch: 8
  val_batch:   1
  num_workers: 20
  pin_memory:  True

G:
  name: resnet_ada_nblocks
  params:
    input_nc:  3
    output_nc: 3
    n_classes: 4
    n_enc1:    3
    n_blocks:  9
    ngf:       32
    norm_type: instance
    dropout:   0.2
    last_ks:   7
  init:
    init_type: normal
    init_gain: 0.02

D:
  name: patch_gan
  params:
    input_nc:  6
    ndf:       32
    n_layers:  3
    norm_type: batch
  init:
    init_type: normal
    init_gain: 0.02

loss:
  cls:
    mode:   focal
    weight: 5.0
  rec:
    mode:   charb
    weight: 10.0
  sim:
    mode:   ssim
    weight: 1.0
  gan:
    mode:   charb
    weight: 1.0

optimizer:
  name: SGD
  params:
    lr:           0.0003
    weight_decay: 0.0

scheduler:
  min_lr: 0.0003
  warmup: 0

trainer:
  epochs:     100
  accum_iter: 1
  ckpt_freq:  1000
  print_freq: 100


...
