---


exp:  resnet_ada_h_v2_exp3
seed: 42

loader:
  norm_method: global_minmax
  train_batch: 4
  val_batch:   1
  num_workers: 20
  pin_memory:  True

G:
  name: resnet_ada_h_nblocks
  params:
    input_nc:  3
    output_nc: 3
    n_classes: 4
    n_enc1:    3
    n_blocks:  9
    ngf:       32
    norm_type: batch
    dropout:   0.2
    last_ks:   7
    lowres:    True
  init:
    init_type: normal
    init_gain: 0.02

D:
  name: patch_gan
  params:
    input_nc:  3
    ndf:       64
    n_layers:  3
    norm_type: batch
  init:
    init_type: normal
    init_gain: 0.02

loss:
  cls:
    mode:   focal
    weight: 5.0
  rec:
    mode:   charb
    weight: 10.0
  sim:
    mode:   ssim
    weight: 1.0
  gan:
    mode:   lsgan
    weight: 1.0

optimizer:
  name: AdamW
  params:
    lr:           0.001
    betas:        [0.5, 0.9]
    weight_decay: 0.05

scheduler:
  min_lr: 0.00001
  warmup: 30

trainer:
  epochs:     100
  accum_iter: 1
  diff_aug:   false
  ema:        false
  ckpt_freq:  1000
  print_freq: 100


...
