---


exp:  baseline_exp3
seed: 42

loader:
  norm_method: global_minmax
  train_batch: 4
  val_batch:   4
  num_workers: 20
  pin_memory:  True

G:
  name: resnet_nblocks
  params:
    input_nc:    3
    output_nc:   3
    n_blocks:    9
    ngf:         64
    norm_type:   batch
    use_dropout: False
  init:
    init_type:   normal
    init_gain:   0.02

D:
  name: patch_gan
  params:
    input_nc:  6
    ndf:       64
    n_layers:  3
    norm_type: batch
  init:
    init_type: normal
    init_gain: 0.02

loss:
  rec:
    mode:   mse
    weight: 10.0
  sim:
    mode:   haarpsi
    weight: 1.0
  gan:
    mode:   lsgan
    weight: 1.0

optimizer:
  name: Adam
  params:
    lr:           0.0003
    betas:        [0.5, 0.999]
    weight_decay: 0.0

scheduler:
  min_lr: 0.00001
  warmup: 0

trainer:
  epochs:     100
  accum_iter: 4
  ckpt_freq:  25
  print_freq: 100


...
