---


exp:  resnet_mod_v2_exp6
seed: 42

loader:
  norm_method: global_minmax
  train_batch: 8
  val_batch:   1
  num_workers: 20
  pin_memory:  true

G:
  name: resnet_mod_nblocks
  params:
    input_nc:  3
    output_nc: 3
    n_classes: 4
    n_enc1:    3
    n_blocks:  9
    ngf:       32
    norm_type: batch
    dropout:   0.2
    last_ks:   7
    lowres:    true
  init:
    init_type: normal
    init_gain: 0.02

D:
  name: ms_gan
  params:
    input_nc:  3
    ndf:       32
    n_layers:  3
    num_D:     3
    norm_type: batch
  init:
    init_type: normal
    init_gain: 0.02

loss:
  cls:
    mode:   focal
    weight: 5.0
  rec:
    mode:   mse
    weight: 10.0
  sim:
    mode:   ssim
    weight: 1.0
  gan:
    mode:   lsgan
    weight: 1.0

optimizer:
  name: AdamW
  params:
    lr:           0.001
    betas:        [0.5, 0.9]
    weight_decay: 0.05

scheduler:
  min_lr: 0.00001
  warmup: 60

trainer:
  epochs:     200
  accum_iter: 1
  diffaug:    false
  ema:        true
  ckpt_freq:  1000
  print_freq: 100


...
